### ISSUE TITLE
v2.1.0 fails with error: Expected "up" | "update" | "refresh" | "destroy" | "preview", but was string in command

### ISSUE THREAD

**Issue by ahanoff** [pulumi/actions#122]
My workflow didn't change for last 10 days. And suddenly started to fail with this error. I'm using latest v2, i.e. current 2.1.0 release. Revert to 2.0.1 fix the issue

## Expected behavior
run update

## Current behavior
Error: Expected "up" | "update" | "refresh" | "destroy" | "preview", but was string in command

## Steps to reproduce

1. Use latest v2
2. 
3.
4.

**Comment by cobraz** [comment]
Hello!

Thank you for reporting this. Are you using any arguments, e.g. `up --refresh`?

Can you share your workflow configuration?

**Comment by ahanoff** [comment]
hi @cobraz, below our pulumi update step

        uses: pulumi/actions@v2
        with:
          command: up --skip-preview --non-interactive --yes
          work-dir: projects/blabla
          stack-name: ${{ env.PULUMI_STACK }}
          github-token: ${{ github.token }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}`

**Comment by cobraz** [comment]
Thanks for that!

We only support using `up`, `update`, `refresh`, `destroy` and `preview` on the `command:` argument.
You don't have to set `--yes`, `--non-interactive`, as they are automatically set.

The `v2` doesn't use the `pulumi` command-line utility. It uses the Pulumi Automation SDK, which does not support setting arguments like `--argument`, which is why we've added some of the [configurable options](https://github.com/pulumi/actions#extra-options).

I will for sure add this to our CHANGELOG/release information, to make other uses know. I'll close this now, but if you have any other issues, please a new issue! Thank you so much!

**Comment by ahanoff** [comment]
> command (required) - The command to pass to the Pulumi CLI. Accepted values are up (update), refresh, destroy and preview. This command is the equivalent of running pulumi <command> if your terminal. Please note, you can pass command arguments as part of this input parameter
https://github.com/pulumi/actions#configuration

hey hey @cobraz , not that fast 🤔 Your readme clearly says I **can pass** arguments

**Comment by cobraz** [comment]
Oh, nice catch! I've updated the `README.md` now. Thanks!

We were supposed to add the ability to set arguments in `command` or as `args`. Pulumi Automation SDK does currently use Pulumi CLI, but in the future, it might not. To make it easier for the Pulumi Github Actions users, we added [named configuration options](https://github.com/pulumi/actions#extra-options).

**Comment by ahanoff** [comment]
>To make it easier for the Pulumi Github Actions users, we added named configuration options.

thanks for link @cobraz , I will try that
