### ISSUE TITLE
Feature Request: Post command outputs as comments

### ISSUE THREAD

**Issue by najohnson** [pulumi/actions#4]
In the terraform github actions repo they actually post the output of terraform plans as comments to the PR: https://github.com/hashicorp/terraform-github-actions/blob/master/plan/entrypoint.sh#L19

Would it be possible to leverage the same thing with pulumi?

**Comment by joeduffy** [comment]
We do have plans to do this. In fact, I saw some comits by @chrsmith recently making progress, so I think this might be imminent. Chris, could you give us an update?

**Comment by chrsmith** [comment]
Yes, we have been doing a lot of work to provide richer output for our logs and comments made from our GitHub Application (https://github.com/apps/pulumi). We should be able to do the same sort of thing when using GitHub Actions as well, though I'd need to take a close look at a few things to make sure we don't emit redundant messages on PRs, etc.

**Comment by joeduffy** [comment]
@najohnson JFYI, the latest release of the GitHub App _should_ show you a summary of Resource Changes, much more like the Terraform Actions support. For example, it looks like this

![image](https://user-images.githubusercontent.com/3953235/51065779-7f47f280-15bb-11e9-986e-c8d0e48554b5.png)

More info on how to install this can be seen here: https://pulumi.io/reference/cd-github.html.

This isn't 100% of what you're asking for -- e.g., I don't think we emit status messages, you still need to install a separate app instead of it happening automatically with Actions, etc. -- but hopefully it gives you something better than what you had before.

**Comment by najohnson** [comment]
thanks for that @joeduffy , I'll try to get that added to our org so I can test it out 👍

**Comment by najohnson** [comment]
FWIW I did end up getting this working by tweaking the entrypoint in this repo and changing the `pulumi $@` to

```
# Run the pulumi command
set +e
OUTPUT=$(sh -c "pulumi --non-interactive $*" 2>&1)
SUCCESS=$?
echo "$OUTPUT"
set -e

# Comment on the PR
COMMENT=""

# If not successful, post failed plan output.
if [ $SUCCESS -ne 0 ]; then
    COMMENT="#### \`pulumi $*\` Failed
\`\`\`
$OUTPUT
\`\`\`"
else
    FMT_PLAN=$(echo "$OUTPUT" | sed -r -e 's/^  \+/\+/g' | sed -r -e 's/^  ~/~/g' | sed -r -e 's/^  -/-/g')
    COMMENT="\`\`\`diff
$FMT_PLAN
\`\`\`"
fi

PAYLOAD=$(echo '{}' | jq --arg body "$COMMENT" '.body = $body')
COMMENTS_URL=$(cat /github/workflow/event.json | jq -r .pull_request.comments_url)
echo "Commenting on PR $COMMENTS_URL"
curl -s -S -H "Authorization: token $GITHUB_TOKEN" --header "Content-Type: application/json" --data "$PAYLOAD" "$COMMENTS_URL"

exit $SUCCESS
```

![image](https://user-images.githubusercontent.com/37184156/51074592-03978580-164f-11e9-97ce-9fccb36708d7.png)
