### ISSUE TITLE
[feature] command prefix for CLI commands

### ISSUE THREAD

**Issue by after-ephemera** [pulumi/actions#893]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

People may want to wrap their call to the `pulumi` CLI with another tool. For example, [Pulumi demonstrates managing more complex Python programs with `poetry`](https://www.pulumi.com/blog/kubernetes-architecture-templates/). In order to run CLI commands successfully in a Poetry project, they need to be prefixed by `poetry run`, such as in the example with `poetry run pulumi up`. This is not possible today with the GH action, and therefore I'm left having to write it by hand instead of using the action.

I propose that a prefix option is added to the action, allowing for arbitrary wrapper commands around CLI calls. This should be doable as a parameter before the command is [exec'ed](https://github.com/pulumi/actions/blob/master/src/libs/pulumi-cli.ts#L16). I'm happy to do so given the green light.

### Affected area/feature

Actions Repo

**Comment by justinvp** [comment]
Thanks for the suggestion, @after-ephemera!

**Comment by RobbieMcKinstry** [comment]
Hmm, my gut feeling is that this feature crosses the boundary of complexity we've tried to establish up until now. I feel it creates a leaky abstraction because the user must know what CLI command is being executed under the hood for it to be useful. Until now, I guidance would have been to use the CLI directly in a `run` step if you need to wrap it in an execution environment.

Also, I'm unsure if it's as simply as augment the `exec` function, since we also use Automation API in a few place, and could potentially lean more heavily on Automation API in the future.

However, Poetry is demonstrative of the benefit. Are there other tools that would benefit as well? I recall some discussion about "monorepo"-style tools that would also need to wrap the CLI.

@cobraz what do you think?

**Comment by RobbieMcKinstry** [comment]
@after-ephemera I appreciate your gracious reply. And I'm very glad to hear you're planning to scale up your use of  Pulumi! ❤️ 
I'm hopeful Pulumi will have more first-class support for Poetry in the near future. I hope that would be sufficient to address your use case! I expect Poetry support would obviate the need for a command prefix :)

**Comment by cobraz** [comment]
Hello, @after-ephemera!

Thank you for this suggestion. As @RobbieMcKinstry said, at the core of this action is the Automation API which is currently wrapping Pulumi CLI. However, Automation API might move away from that, so we've tried to keep the _CLI relationship_ to a minimum.

Other than that, we've tried to support _most use cases_, but that said, I would love to learn more about how we can support this more abstractly. I haven't personally used Poetry, so I don't know the inner workings of it.

Again, thanks for submitting this! ❤️

**Comment by ma-ts** [comment]
Hi @after-ephemera! I've recently struggled with this myself, however the Pulumi CLI and the actual code that is running for your deployment are separate from each other (the Pulumi CLI this action uses is even installed by the action itself).

In order to use Pulumi with the correct Poetry env, you can add the following to the poetry.toml in your work dir:

```
[virtualenvs]
in-project = true
```

And then in your Pulumi.yaml, use the following venv configuration:

```
runtime:
  name: python
  options:
    virtualenv: .venv
```

It will then just use the python (and libraries) from poetry!

**Comment by after-ephemera** [comment]
Wow this is actually amazing, thank you! I will need to do some refactoring in my stacks but this should solve my problem.
