### ISSUE TITLE
Add support for Review Pulumi Stacks

### ISSUE THREAD

**Issue by ziahamza** [pulumi/actions#9]
Allow the ability for Pulumi stack to be automatically created / destroyed with each PR. This would be a super cool feature to dynamically test preview links for infrastructure changes without having to merge to staging branch.

**Comment by ziahamza** [comment]
More than happy to send a series of PRs, with this being the first: https://github.com/pulumi/actions/pull/8

**Comment by chrsmith** [comment]
Hey @ziahamza , sorry for the delay in getting to this! It's been snowing in Seattle, which evidently means that my entire life has been chaos. I'll take a look at the PR you linked.

As for this particular issue, and dynamically standing up Pulumi stacks for review, it's an interesting idea to be sure. I'd defer to @lukehoban or @d-nishi on how we would want to prioritizing adding such a capability.

I can definitely see us adding support or a hook so that you could dynamically create a new stack and run `pulumi update` when CI/CD runs for a pull request. But the problem I see is that we'd need to be careful in understanding the lifetime of cloud resources associated with that stack.

Today, most CI/CD systems we support don't have a good story for hooking into the "pull request closed" type event. Pulumi's GitHub app doesn't control the execution environment, rather, the user-provided CI/CD system does. In other words, Pulumi doesn't initiate the stack update, it's up to how TravisCI, CircleCI, or GitHub actions were configured.

So in order for this scenario to work, the repo's GitHub actions would need to explicitly register an event for the `pull_request` event's "closed" action, and then start the workflow to destroy the PR-specific stack... which is probably doable.

If you are eager to work on this scenario, I'd suggest just forking this repo and seeing if you can hack together the complete end-to-end experience. Starting from that we can see what we can simplify and if the net-result is something that would work in-practice. And if not, understand what feature(s) we would need to add to the CLI or Pulumi Service to make it work.

**Comment by stack72** [comment]
Closed as being tracked in #40
